module.exports = {
  docs: {
    "Getting Started": [
      "introduction",
      "installation",
      "tutorial",
      // 'examples-dev',
      // 'examples-nondev',
    ],
    Features: [
      "features",
      // 'gen-code',
      "gen-diagram",
      // 'gen-docs',
      // 'gen-db',
      // 'gen-test',
    ],
    "Advanced Guides": [
      "lang-spec",
      {
        "Command Documentation": [
          "cmd",
          "common-flags",
          "cmd-validate",
          "cmd-diagram",
          "cmd-info",
          "cmd-env",
          "cmd-sd",
          "cmd-integrations",
          "cmd-datamodel",
          // 'cmd-db',
          // 'cmd-db-delta',
          // 'cmd-codegen',
          "cmd-import",
          "cmd-export",
          "cmd-protobuf",
          "cmd-repl",
          // 'cmd-template',
        ],
      },
      // 'plugin',
    ],
  },
  community: ["discussions", "resources", "faq"],
};
