# https://github.com/marketplace/actions/github-spellcheck-action
name: Spellcheck
on: push

jobs:
  spell_check:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: rojopolis/spellcheck-github-actions@0.5.0
        name: Spellcheck
